### ISSUE TITLE
OJ version isn't compiling

### ISSUE THREAD

**Issue by glassputan** [teamsnap/teamsnap_rb#88]
Trying to build this against Ruby 2.4.0.  The gem oj (build 2.11.5) is throwing exceptions and the build is failing.  Switching to the latest oj (build 2.18.1) fixes the issue.  I don't seem to have access to this repo, so I had to download it and edit it locally.

**Comment by knappe** [comment]
Hey @glassputan, thanks for filing the issue!  I don't think we've yet upgraded to ruby 2.4 -- I'm able to duplicate the oj install issue:

```
Gem files will remain installed in /home/knappe/.rvm/gems/ruby-2.4.0-rc1/gems/oj-2.11.5 for inspection.
Results logged to /home/knappe/.rvm/gems/ruby-2.4.0-rc1/extensions/x86_64-linux/2.4.0/oj-2.11.5/gem_make.out
An error occurred while installing oj (2.11.5), and Bundler cannot continue.
Make sure that `gem install oj -v '2.11.5'` succeeds before bundling.
```

I'd suggest reverting to 2.2 (https://github.com/teamsnap/teamsnap_rb/blob/master/.travis.yml#L9 is the latest we support) until we upgrade to 2.4.

**Comment by knappe** [comment]
@glassputan We've upgraded `oj` to support ruby 2.4.  Please let us know if you're still running into issues! 👍
